### ISSUE TITLE
Add some "About" information to the repository on github, and a README.

### ISSUE THREAD

**Issue by tomprince** [neubee/spirit-island-builder#125]
It would be useful to have some information about what this repository is.

I was looking for at least a link to (I presume) https://spirit-island-builder.pages.dev/, so I could get back to the live version from the repository.

It might also make sense to have a link to this repository from somewhere on that site.

**Comment by tomprince** [comment]
Or, maybe the appropriate web page is https://spirit-island-builder.pages.dev/ (although, ideally, one would redirect to the other).

**Comment by neubee** [comment]
#126

**Comment by neubee** [comment]
Good idea, thanks for the suggestions!

Which did you find first, the website or this repo?

> (although, ideally, one would redirect to the other).

Unfortunately we can't get that exact behavior due to how cloudflare pages works. spiritislandbuilder.com has CNAME records that point to https://spirit-island-builder.pages.dev/ but we aren't able to make https://spirit-island-builder.pages.dev/ redirect to spiritislandbuilder.com/

**Comment by neubee** [comment]
Ignore the bit about CNAME records, looks like cloudflare is just using A records instead. Either way, we can't do the spirit-island-builder.pages.dev to spiritislandbuilder.com redirect.

**Comment by tomprince** [comment]
> Which did you find first, the website or this repo?

I was linked to the `.pages.dev` site first, from which I followed the link to the instructions (on github pages) and thence to here. But then I had closed the website but still had github open, and wanted to navigate back.

**Comment by tomprince** [comment]
> > (although, ideally, one would redirect to the other).
> 
> Unfortunately we can't get that exact behavior due to how cloudflare pages works. spiritislandbuilder.com has CNAME records that point to https://spirit-island-builder.pages.dev/ but we aren't able to make https://spirit-island-builder.pages.dev/ redirect to spiritislandbuilder.com/

https://community.cloudflare.com/t/301-cloudflare-page-to-custom-domain-with-redirects/425445 has a suggestion on how to setup the redirection.

**Comment by neubee** [comment]
Ohhh, nice find

@resonant-gamedesign take a look at https://developers.cloudflare.com/pages/how-to/www-redirect/ and see if you can get a spirit-island-builder.pages.dev/ to https://spiritislandbuilder.com/ redirect working. 
It looks like the "source URL" should be `spirit-island-builder.pages.dev` and the target will be `https://spiritislandbuilder.com`.
I can assist with the configuration is you have any issues.

**Comment by tomprince** [comment]
In addition to the README, this is the "about" information I was talking about. ![Screen Shot 2022-12-20 at 09 38 17](https://user-images.githubusercontent.com/283816/208719705-8c0c7384-97c7-45b7-bda3-39646a55ab26.png)

**Comment by resonant-gamedesign** [comment]
I think it works!
