### ISSUE TITLE
Change to autocomplete

### ISSUE THREAD

**Issue by resonant-gamedesign** [neubee/spirit-island-builder#166]
This is a request not an issue... but

I would like autocomplete to identify when the autcomplete ends with an open parenthesis, and automatically close the parenthesis, but leave the cursor between the parenthesis.

ie.
add-presence(|)

where | is the keyboard cursor.

**Comment by resonant-gamedesign** [comment]
@neubee any chance you could look at this?

**Comment by neubee** [comment]
#212
