### ISSUE TITLE
Auto updating preview issues

### ISSUE THREAD

**Issue by neubee** [neubee/spirit-island-builder#177]
@resonant-gamedesign 
The following presence track option do not auto update correctly.

* load the "finder" example board
* Expand the presence tracks
* Focus and then un-focus the "middle(1+moon)" input
* The icon for the node will disappear and the text will display "Middle, Moon)"
* If you click the Update Preview button the node will render correctly

**Comment by resonant-gamedesign** [comment]
Certain features won't work with this method. I've tried to identify when something like that has happened and make the 'update preview' button flash.
Ideally, I'll instead just run the function that reloads the preview, but I can't figure out how to get that function to pass to other components.

**Comment by tomprince** [comment]
It feels like this solution to get a reactive preview requires a bunch more complicated code to handle something that svelte is *designed* to handle directly. It feels like this solution is going to be more fragile than writing the svelte code to render things directly.

**Comment by resonant-gamedesign** [comment]
I understand that I'm not doing things the right way. But it's how I'm
doing it. And it actually wasn't a lot of work, at all. And I still don't
think that we can solve this thing without multipass. And maybe that's
possible with Svelte integration? Or maybe Svelte integration is possible
without abandoning the template?

I'm worried that we're pushing in opposite directions.
