### ISSUE TITLE
Move footer to bottom of page

### ISSUE THREAD

**Issue by resonant-gamedesign** [neubee/spirit-island-builder#223]
And I think they're wider than before?
![image](https://user-images.githubusercontent.com/44596045/215533009-001dcb9c-8582-477a-96d3-fb096dd5a18e.png)

**Comment by resonant-gamedesign** [comment]
This issue does not appear on the Spirit Board Play Side, but on all other components.

**Comment by resonant-gamedesign** [comment]
This is happening because Bulma has a last:child option on the columns that gives them a negative margin. HOWEVER, only on the Play side are the columns NOT the last child, because the invisible modal. This wasn't a problem before because I had the hidden 'holder frame'.
Easy to fix. Not sure if we should fix through CCS.

**Comment by neubee** [comment]
As far as I know CSS is the only option.

**Comment by resonant-gamedesign** [comment]
I fixed this.

**Comment by neubee** [comment]
Ohh, I see. I think I would prefer to have the thing be at the bottom of the page.

**Comment by resonant-gamedesign** [comment]
Partially fixed. New issue:
![Screenshot 2023-02-04 at 17-30-58 Spirit Island Builder](https://user-images.githubusercontent.com/44596045/216793308-9da48090-662c-4a06-9186-fe8c451123ec.png)
