### ISSUE TITLE
Cannot open files anymore 

### ISSUE THREAD

**Issue by LatentOctopus** [neubee/spirit-island-builder#234]
I have some files that I saved a week ago. I used to be able to open them, but I tried today and I couldn't. Not sure what info could be useful to provide to debug.

**Comment by neubee** [comment]
@LatentOctopus This should be fixed now

**Comment by LatentOctopus** [comment]
This happened again, in a different form: I now can't select the file to open (can browse directories, but I'm never able to select a file). It doesn't even work with a file I just saved, so it's not a compatibility problem.

I tested on two different Android devices, both on Chrome and Firefox.
