### ISSUE TITLE
BUG: 'Load' from HTML file functionality broken for Spirit Board Play Side

### ISSUE THREAD

**Issue by budn8** [neubee/spirit-island-builder#235]
When pressing "Load" and selecting a previously saved spirit file, the data fails to load into the template for the Spirit Board Play Side. The other tabs (Lore Side, Power Cards, etc.) seem to work just fine when loading from a save. 

I cloned the project to see if I could fix this issue myself and raise a PR, but I am unfamiliar with Svelte so figured I would at least try to provide a detailed bug report instead. I wasn't sure if this is the same issue reported as #234, so I made a new issue. Feel free to close/combine if needed. 

---

The failure seems to be caused by loading spirit files that use one of the Example Banner assets: 
```
Uncaught (in promise) TypeError: URL constructor: /template/MyCustomContent/BannerExamples/banner-fractalmist.png is not a valid URL.
    maybeResolveURL lib.js:328
    readHTML index.svelte:361
    loadHTMLFromURL index.svelte:155
    handleInput load-button.svelte:16
```

**As a workaround,** manually removing all instances of the path `/template/MyCustomContent/BannerExamples/banner-fractalmist.png` from the exported HTML files fixed the issue for me--the other data loaded just fine after that.

**Comment by neubee** [comment]
@budn8 This should be fixed now
