### ISSUE TITLE
Images moving during screenshot

### ISSUE THREAD

**Issue by resonant-gamedesign** [neubee/spirit-island-builder#257]
I've noticed an issue with screenshot. If you're using the annotated presence node option (Examples -> Add Presence uses a few), and then you export a screenshot, you'll notice that the little icons above the presence nodes are lower in the screenshot than in the displayed board.

screenshot
![image](https://user-images.githubusercontent.com/44596045/220973532-350323a4-4acd-49fb-b7db-3a1ab1373cfd.png)

displayed board:
![image](https://user-images.githubusercontent.com/44596045/220973457-4039e500-731d-4691-b797-e3af7aa1b3d2.png)

notice how the first icon overlaps the P in play?

I can't figure out what is making them move slightly. I had a similar issue with the banners, but 'solved' it by optimizing it for the screenshot (so it looks off in the display, but in this case its so minor as to not be noticed). I can't use the same solution here.

**Comment by tomprince** [comment]
I think that is probably an issue with [html2canvas](https://github.com/niklasvh/html2canvas/). Note that it isn't technically taking a screenshot, but rather drawing an image that is designed to match the HTML. As I understand it, it uses a combination of parsing the HTML and CSS (along with knowledge of how to render a lot of it), along with (perhaps) looking at some of the layout information that you can get by looking at the DOM.

One thing that occurs to me: if the icons are currently being rendered as background images with CSS, you might get more consistent behaviour by switching to using `<img>` tags instead. I *think* that html2canvas needs to figure out where to layout the image itself, when using `background-image` in CSS, but can read the exact position from the element when there is an `<img>` tag.
