### ISSUE TITLE
Resolution of DownloadImage/Screenshot

### ISSUE THREAD

**Issue by resonant-gamedesign** [neubee/spirit-island-builder#263]
Is there a way to increase the resolution of the downloaded image? For example, if we doubled all of the dimensions, would it increase the image size? That would be a nightmare, but good to know if its an option (scale doesn't seem to do it).

**Comment by neubee** [comment]
Setting the scale here https://github.com/neubee/spirit-island-builder/blob/dev/src/lib/preview-frame/take-screenshot.js#L11 does seem to do what you're asking for. When I set the scale to 2 I get an image that is twice as big as when the scale is set to 1.

**Comment by resonant-gamedesign** [comment]
It does actually allow for both a higher resolution and seemingly higher quality image, though that might depend on the image for a particular icon:
![image](https://user-images.githubusercontent.com/44596045/223939626-ca4107c5-a830-4675-b8fd-0b18fa135806.png)
vs.
![image](https://user-images.githubusercontent.com/44596045/223939656-39e811ca-f53f-48aa-8d6c-c237bf2491ef.png)

**Comment by resonant-gamedesign** [comment]
Any guess as to why the images are creating those edge lines? Like above the fire element?

**Comment by neubee** [comment]
No idea, but it seems likely that html2canvas is introducing them. I see the lines at a scale of 1 as well. You can open an issue at https://github.com/niklasvh/html2canvas or dive into the html2canvas code to see exactly how it is rendering these.

**Comment by resonant-gamedesign** [comment]
I didn't even realize that was an option. Can we change our local copy if I decide to mess with their code?
This seems like a place to start: https://github.com/niklasvh/html2canvas/blob/master/src/render/background.ts

**Comment by neubee** [comment]
Yes, we can use a customized version of html2canvas by forking it on github and then installing the forked version with `npm`. Or, if you're able to fix a bug that would be helpful to other people using the library, you can make a PR to html2canvas directly.
