### ISSUE TITLE
iframes are being created multiple times

### ISSUE THREAD

**Issue by neubee** [neubee/spirit-island-builder#53]
Not really sure how it works, but here's something I noticed. Under 'sources', it looks like we keep generating new frames endlessly.

![image](https://user-images.githubusercontent.com/4044095/194225299-553978b5-56d3-4d1e-81f8-b8f451288b99.png)

**Comment by resonant-gamedesign** [comment]
Yes, I noticed this too. I was going to flag it for you.
It doesn't ALWAYS happen. Haha. Seems to be connected to when the preview fails to load, so its possible it will just go away when we fix that.
I do wonder how iframes with IDs (which are unique, right?) can coexist.

**Comment by neubee** [comment]
Oh, you did. I just copied over the email that you sent to me.

Technically HTML element IDs are supposed to be unique, but I don't know if any browsers are actually enforcing that. In my experience you can use the same ID as many times as you like.

**Comment by tomprince** [comment]
Are there actually multiple iframes created at once, or is whatever you are showing there (I'm guessing chrome dev tools?) getting confused by deleting and then recreating iframes in succession?

**Comment by resonant-gamedesign** [comment]
I'm not sure, but lets see if your html refactor solves this...
