### ISSUE TITLE
Font changes

### ISSUE THREAD

**Issue by neubee** [neubee/spirit-island-builder#94]
@resonant-gamedesign is there a reason to keep all the "extra" stuff in the font directories? I'm talking about poster, installation instructions, ffonts.net.*, etc.

Should we include some kind of attribution for the fonts?

I'm assuming someone contacted the DKSnemand guy and was told not to use the font? The license seems very permissive, so I'm surprised he would have said no.

**Comment by resonant-gamedesign** [comment]
No reason to keep the stuff in the folder. I just didn't think about it.

I did contact a website, not the author.
